name: AutoUpdate

on:
  push:
    branches:
      - 'main'
      - 'dev'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: hzz07/GoodManWEN.github.io
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build
        run: |
          git config --global core.quotepath false
          git ls-files | while read file; do touch -d $(git log -1 --format="@%ct" "$file") "$file"; done
          python3 generate.py
          npm install
          npm run build
      - name: Commit files
        run: |
          git config --local user.email "1032325608@qq.com"
          git config --local user.name "hzz BOT"
          git add .
          git commit -m "update built files after user commit"
      - name: Push changes
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS }}
          REPOSITORY_NAME: hzz07/hzz07.github.io
          BRANCH: master
          FOLDER: .


